version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - postgres
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mydatabase
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  mongo:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  pg-data:
